function(require_file path)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Missing jobs example file: ${path}")
    endif()
endfunction()

function(require_match text pattern label)
    string(FIND "${text}" "${pattern}" found)
    if(found LESS 0)
        message(FATAL_ERROR "Jobs example ${label} is missing pattern: ${pattern}")
    endif()
endfunction()

set(example_root "${PROJECT_SOURCE_DIR}/examples")
foreach(case_name IN ITEMS jobs-basic jobs-recurring jobs-postgres-worker jobs-sqlserver-worker)
    if(case_name STREQUAL "jobs-sqlserver-worker")
        require_file("${example_root}/${case_name}/main.ts")
        require_file("${example_root}/${case_name}/README.md")
        file(READ "${example_root}/${case_name}/main.ts" app_js)
        file(READ "${example_root}/${case_name}/README.md" readme_md)
    else()
    require_file("${example_root}/${case_name}/app.js")
    require_file("${example_root}/${case_name}/README.md")
    file(READ "${example_root}/${case_name}/app.js" app_js)
    file(READ "${example_root}/${case_name}/README.md" readme_md)
    endif()
    require_match("${app_js}" "Jobs.create" "${case_name} creates Jobs runtime")
    require_match("${app_js}" "Jobs.storage" "${case_name} creates Jobs storage")
    require_match("${app_js}" "jobs.define" "${case_name} defines durable jobs")
    require_match("${app_js}" "jobs.storage.init" "${case_name} initializes scheduler schema")
    require_match("${readme_md}" "Jobs" "${case_name} README names Jobs")
endforeach()

foreach(case_name IN ITEMS jobs-basic jobs-recurring jobs-postgres-worker jobs-sqlserver-worker jobs-stress)
    require_file("${example_root}/${case_name}/main.ts")
    file(READ "${example_root}/${case_name}/main.ts" program_ts)
    require_match("${program_ts}" "export async function main" "${case_name} Program Mode main")
    require_match("${program_ts}" "jobs.storage.init" "${case_name} Program Mode schema init")
endforeach()

file(READ "${example_root}/jobs-basic/app.js" basic_js)
require_match("${basic_js}" "data.sqlite.open" "jobs-basic provider")
require_match("${basic_js}" "jobs.enqueue" "jobs-basic enqueue")
require_match("${basic_js}" "idempotencyKey" "jobs-basic idempotency")
require_match("${basic_js}" "payloadRedactionKeys" "jobs-basic redaction")
require_match("${basic_js}" "worker.runOnce" "jobs-basic worker")

file(READ "${example_root}/jobs-recurring/app.js" recurring_js)
require_match("${recurring_js}" "data.sqlite.open" "jobs-recurring provider")
require_match("${recurring_js}" "jobs.recurring" "jobs-recurring recurring API")
require_match("${recurring_js}" "tickRecurring" "jobs-recurring tick")
require_match("${recurring_js}" "cron" "jobs-recurring cron")

file(READ "${example_root}/jobs-postgres-worker/app.js" postgres_js)
require_match("${postgres_js}" "data.postgres.open" "jobs-postgres-worker provider")
require_match("${postgres_js}" "createWorker" "jobs-postgres-worker worker")
require_match("${postgres_js}" "worker.start" "jobs-postgres-worker start")

file(READ "${example_root}/jobs-sqlserver-worker/main.ts" sqlserver_ts)
require_match("${sqlserver_ts}" "data.sqlserver.open" "jobs-sqlserver-worker provider")
require_match("${sqlserver_ts}" "createWorker" "jobs-sqlserver-worker worker")
require_match("${sqlserver_ts}" "worker.runOnce" "jobs-sqlserver-worker run")
