if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()
if(NOT DEFINED CMAKE_BINARY_DIR)
    message(FATAL_ERROR "CMAKE_BINARY_DIR is required")
endif()
if(NOT DEFINED SLOPPY_CLI)
    message(FATAL_ERROR "SLOPPY_CLI is required")
endif()
if(NOT DEFINED SLOPPYC_EXECUTABLE)
    message(FATAL_ERROR "SLOPPYC_EXECUTABLE is required")
endif()
if(NOT DEFINED SLOPPY_CASE)
    message(FATAL_ERROR "SLOPPY_CASE is required")
endif()
if(NOT DEFINED SLOPPY_EXPECTED_ERROR)
    set(SLOPPY_EXPECTED_ERROR "")
endif()
if(NOT DEFINED SLOPPY_EXPECTED_OUTPUT)
    set(SLOPPY_EXPECTED_OUTPUT "")
endif()
if(NOT DEFINED SLOPPY_EXPECTED_PLAN)
    set(SLOPPY_EXPECTED_PLAN "")
endif()
if(NOT DEFINED SLOPPY_EXPECTED_PLAN_SECONDARY)
    set(SLOPPY_EXPECTED_PLAN_SECONDARY "")
endif()
if(NOT DEFINED SLOPPY_EXPECTED_SOURCE_MAP)
    set(SLOPPY_EXPECTED_SOURCE_MAP "")
endif()
if(NOT DEFINED SLOPPY_COMMAND)
    set(SLOPPY_COMMAND "run")
endif()

set(work_dir "${CMAKE_BINARY_DIR}/source-input-run/${SLOPPY_CASE}")
file(REMOVE_RECURSE "${work_dir}")
file(MAKE_DIRECTORY "${work_dir}")

if(DEFINED SLOPPY_PROJECT_FIXTURE)
    file(COPY "${PROJECT_SOURCE_DIR}/${SLOPPY_PROJECT_FIXTURE}/" DESTINATION "${work_dir}")
endif()

set(run_args "${SLOPPY_COMMAND}")
if(DEFINED SLOPPY_SOURCE)
    list(APPEND run_args "${PROJECT_SOURCE_DIR}/${SLOPPY_SOURCE}")
endif()
if(DEFINED SLOPPY_ENVIRONMENT)
    list(APPEND run_args --environment "${SLOPPY_ENVIRONMENT}")
endif()
if(DEFINED SLOPPY_OUT_DIR)
    list(APPEND run_args --out "${SLOPPY_OUT_DIR}")
endif()
if(DEFINED SLOPPY_EXTRA_ARGS)
    list(APPEND run_args ${SLOPPY_EXTRA_ARGS})
endif()
if(DEFINED SLOPPY_CONFIG_ENTRY)
    file(WRITE "${work_dir}/sloppy.json" "${SLOPPY_CONFIG_ENTRY}")
endif()
if(DEFINED SLOPPY_CONFIG_SOURCE)
    file(COPY_FILE "${PROJECT_SOURCE_DIR}/${SLOPPY_CONFIG_SOURCE}" "${work_dir}/app.js")
endif()
if(DEFINED SLOPPY_ONCE_METHOD AND SLOPPY_COMMAND STREQUAL "run")
    list(APPEND run_args --once "${SLOPPY_ONCE_METHOD}" "${SLOPPY_ONCE_TARGET}")
endif()

execute_process(
    COMMAND "${CMAKE_COMMAND}" -E env "SLOPPY_SLOPPYC=${SLOPPYC_EXECUTABLE}" "${SLOPPY_CLI}"
            ${run_args}
    WORKING_DIRECTORY "${work_dir}"
    TIMEOUT 180
    RESULT_VARIABLE result
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr)

if(SLOPPY_EXPECTED_ERROR)
    if(result EQUAL 0)
        message(FATAL_ERROR "source-input ${SLOPPY_COMMAND} unexpectedly succeeded\nstdout:\n${stdout}\nstderr:\n${stderr}")
    endif()
    if(NOT stderr MATCHES "${SLOPPY_EXPECTED_ERROR}")
        message(
            FATAL_ERROR
                "source-input ${SLOPPY_COMMAND} did not report expected error '${SLOPPY_EXPECTED_ERROR}'\nstdout:\n${stdout}\nstderr:\n${stderr}")
    endif()
else()
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "source-input ${SLOPPY_COMMAND} failed\nstdout:\n${stdout}\nstderr:\n${stderr}")
    endif()
    if(SLOPPY_EXPECTED_OUTPUT)
        string(REGEX MATCH "${SLOPPY_EXPECTED_OUTPUT}" output_match "${stdout}")
        if(NOT output_match)
            message(
                FATAL_ERROR
                    "source-input ${SLOPPY_COMMAND} output did not match '${SLOPPY_EXPECTED_OUTPUT}'\nstdout:\n${stdout}\nstderr:\n${stderr}")
        endif()
    endif()
endif()

if(DEFINED SLOPPY_EXPECTED_ARTIFACT_DIR)
    set(artifact_dir "${work_dir}/${SLOPPY_EXPECTED_ARTIFACT_DIR}")
    foreach(artifact IN ITEMS app.plan.json app.js app.js.map)
        if(NOT EXISTS "${artifact_dir}/${artifact}")
            message(FATAL_ERROR "source-input ${SLOPPY_COMMAND} did not emit ${artifact} under ${artifact_dir}")
        endif()
    endforeach()
    file(READ "${artifact_dir}/app.plan.json" plan_json)
    if(NOT plan_json MATCHES "\"sourceMap\"")
        message(FATAL_ERROR "source-input app.plan.json does not reference sourceMap")
    endif()
    file(READ "${artifact_dir}/app.js.map" source_map_json)
    if(NOT source_map_json MATCHES "\"x_sloppy\"")
        message(FATAL_ERROR "source-input app.js.map does not include Sloppy source-map metadata")
    endif()
    if(NOT source_map_json MATCHES "\"sourceFiles\"")
        message(FATAL_ERROR "source-input app.js.map does not include source file metadata")
    endif()
    if(SLOPPY_EXPECTED_PLAN)
        if(NOT plan_json MATCHES "${SLOPPY_EXPECTED_PLAN}")
            message(
                FATAL_ERROR
                    "source-input app.plan.json did not match '${SLOPPY_EXPECTED_PLAN}'\nplan:\n${plan_json}")
        endif()
    endif()
    if(SLOPPY_EXPECTED_PLAN_SECONDARY)
        if(NOT plan_json MATCHES "${SLOPPY_EXPECTED_PLAN_SECONDARY}")
            message(
                FATAL_ERROR
                    "source-input app.plan.json did not match '${SLOPPY_EXPECTED_PLAN_SECONDARY}'\nplan:\n${plan_json}")
        endif()
    endif()
    if(SLOPPY_EXPECTED_SOURCE_MAP)
        if(NOT source_map_json MATCHES "${SLOPPY_EXPECTED_SOURCE_MAP}")
            message(
                FATAL_ERROR
                    "source-input app.js.map did not match '${SLOPPY_EXPECTED_SOURCE_MAP}'\nsource map:\n${source_map_json}")
        endif()
    endif()
endif()
