const __sloppyRuntime = globalThis.__sloppy_runtime;
if (__sloppyRuntime === undefined) {
  throw new Error("Sloppy bootstrap runtime was not loaded");
}
const { Environment, Results, column, data, orm, relation, table } = __sloppyRuntime;

const OrmTeams = table("sloppy_pg_orm_teams", {
  id: column.int().primaryKey(),
  name: column.text().notNull(),
});

const OrmUsers = table("sloppy_pg_orm_users", {
  id: column.int().primaryKey(),
  teamId: column.int().notNull().references(() => OrmTeams.id),
  email: column.text().notNull(),
  displayName: column.text().nullable(),
  version: column.int().notNull().concurrencyToken(),
});

relation(OrmUsers, ({ one }) => ({
  team: one(OrmTeams, {
    local: OrmUsers.teamId,
    foreign: OrmTeams.id,
  }),
}));

relation(OrmTeams, ({ many }) => ({
  users: many(OrmUsers, {
    local: OrmTeams.id,
    foreign: OrmUsers.teamId,
  }),
}));

async function execStatements(db, sql) {
  for (const statement of sql.split(";").map((item) => item.trim()).filter(Boolean)) {
    await db.exec(statement);
  }
}

async function runOrmLane(db) {
  await db.exec("drop table if exists sloppy_pg_orm_users");
  await db.exec("drop table if exists sloppy_pg_orm_teams");
  await execStatements(db, orm.migrations.script([OrmUsers, OrmTeams], { provider: "postgres" }));

  await OrmTeams.insert(db, { id: 1, name: "Core" }).execute();
  await OrmUsers.insert(db, {
    id: 1,
    teamId: 1,
    email: "ada.orm@example.com",
    displayName: "Ada",
    version: 1,
  }).execute();
  const selected = await OrmUsers.findById(db, 1);
  await OrmUsers.updateById(db, 1, { displayName: "Ada Byron" }, { expected: { version: 1 } });
  let conflict = false;
  try {
    await OrmUsers.updateById(db, 1, { displayName: "Ada Again" }, { expected: { version: 1 } });
  } catch (error) {
    conflict = error?.code === "SLOPPY_ORM_CONCURRENCY_CONFLICT";
  }
  const oneInclude = await orm.from(OrmUsers).where((u) => u.id.eq(1)).include((u) => u.team).singleOrDefault(db);
  const manyInclude = await orm.from(OrmTeams).where((t) => t.id.eq(1)).include((t) => t.users, { strategy: "split" }).singleOrDefault(db);
  try {
    await orm.transaction(db, async (tx) => {
      await OrmUsers.insert(tx, { id: 999, teamId: 1, email: "rollback.orm@example.com", displayName: null, version: 1 }).execute();
      throw new Error("rollback");
    });
  } catch {
  }
  const rolledBack = await OrmUsers.findById(db, 999);
  const raw = await orm.query(db, orm.sql.postgres`select count(*)::int as count from sloppy_pg_orm_users`);
  for (let id = 2; id <= 132; id += 1) {
    await OrmUsers.insert(db, { id, teamId: 1, email: `cursor-${id}@orm.example.com`, displayName: null, version: 1 }).execute();
  }
  let cursorCount = 0;
  const ormCursor = await orm.from(OrmUsers).orderBy((u) => u.id.asc()).cursor(db, { batchSize: 32 });
  try {
    for await (const row of ormCursor) {
      if (row.id > 0) {
        cursorCount += 1;
      }
    }
  } finally {
    await ormCursor.close();
  }
  await OrmUsers.deleteById(db, 1, { expected: { version: 2 } });

  return {
    selectedEmail: selected.email,
    conflict,
    oneInclude: oneInclude.team.name,
    manyIncludeCount: manyInclude.users.length,
    rolledBack: rolledBack === null,
    rawCount: raw[0].count,
    cursorCount,
  };
}

globalThis.__sloppy_handler_1 = async () => {
  try {
    const connectionString = Environment.get("SLOPPY_POSTGRES_TEST_URL");
    if (connectionString.length === 0) {
      throw new Error("SLOPPY_POSTGRES_TEST_URL is required for the PostgreSQL live bridge lane");
    }

    const db = data.postgres.open({
      connectionString,
      capability: "data.main",
      maxConnections: 1,
    });
    try {
      await db.exec("drop table if exists sloppy_pg_bridge_cursor");
      await db.exec("create table sloppy_pg_bridge_cursor (id int generated by default as identity primary key, name text not null)");
      await db.exec("insert into sloppy_pg_bridge_cursor (name) values ($1)", ["Ada"]);
      await db.transaction(async (tx) => {
        await tx.exec("insert into sloppy_pg_bridge_cursor (name) values ($1)", ["Grace"]);
        const txCursor = await tx.queryCursor("select name from sloppy_pg_bridge_cursor order by id", [], { batchSize: 1 });
        try {
          const txNames = [];
          for await (const row of txCursor) {
            txNames.push(row.name);
          }
          if (txNames.length !== 2) {
            throw new Error("postgres transaction cursor did not read expected rows");
          }
        } finally {
          await txCursor.close();
        }
      });
      await db.exec("insert into sloppy_pg_bridge_cursor (name) select 'User-' || value::text from generate_series(1, 150) as value");

      let materializedRejected = false;
      try {
        await db.query("select id, name from sloppy_pg_bridge_cursor order by id", []);
      } catch (error) {
        materializedRejected = String(error && error.message ? error.message : error).includes("exceeded max rows");
      }

      const cursorRows = [];
      const cursor = await db.queryCursor("select id, name from sloppy_pg_bridge_cursor order by id", [], { batchSize: 32 });
      try {
        for await (const row of cursor) {
          cursorRows.push(row.name);
        }
      } finally {
        await cursor.close();
      }

      const rawCursor = await db.queryRawCursor("select id, name from sloppy_pg_bridge_cursor order by id", [], { batchSize: 16, maxRows: 2 });
      let rawFirst = null;
      let cursorMaxRowsRejected = false;
      try {
        rawFirst = await rawCursor.next();
        await rawCursor.next();
        await rawCursor.next();
      } catch (error) {
        cursorMaxRowsRejected = String(error && error.message ? error.message : error).includes("exceeded max rows");
      } finally {
        await rawCursor.close();
      }

      const pinnedCursor = await db.queryCursor("select id, name from sloppy_pg_bridge_cursor order by id", [], { batchSize: 8 });
      let poolPinned = false;
      try {
        await pinnedCursor.next();
        try {
          await db.queryOne("select 1 as ok", []);
        } catch (error) {
          poolPinned = String(error && error.message ? error.message : error).includes("pool is exhausted");
        }
      } finally {
        await pinnedCursor.close();
      }
      const afterClose = await db.queryOne("select count(*)::int as count from sloppy_pg_bridge_cursor", []);

      let cursorTimedOut = false;
      try {
        const timeoutCursor = await db.queryCursor("select pg_sleep(0.01), value from generate_series(1, 100) as value", [], { timeoutMs: 50 });
        try {
          for await (const row of timeoutCursor) {
            if (row.value < 0) {
              throw new Error("unreachable");
            }
          }
        } finally {
          await timeoutCursor.close();
        }
      } catch (error) {
        cursorTimedOut = String(error && error.message ? error.message : error).includes("deadline was exceeded");
      }

      let postgresTimedOut = false;
      try {
        await db.query("select pg_sleep(2)", [], { timeoutMs: 50 });
      } catch (error) {
        postgresTimedOut = String(error && error.message ? error.message : error).includes("deadline was exceeded");
      }
      const users = await db.query("select id, name from sloppy_pg_bridge_cursor where name in ($1, $2) order by id", ["Ada", "Grace"]);
      const ormLane = await runOrmLane(db);
      return Results.json({
        users,
        postgresTimedOut,
        materializedRejected,
        cursorCount: cursorRows.length,
        cursorFirst: cursorRows[0],
        cursorLast: cursorRows[cursorRows.length - 1],
        rawFirst,
        cursorMaxRowsRejected,
        poolPinned,
        afterCloseCount: afterClose.count,
        cursorTimedOut,
        ormLane,
      });
    } finally {
      try {
        await db.exec("drop table if exists sloppy_pg_orm_users");
        await db.exec("drop table if exists sloppy_pg_orm_teams");
        await db.exec("drop table if exists sloppy_pg_bridge_cursor");
      } catch {
      }
      db.close();
    }
  } catch (error) {
    return Results.text(String(error && error.message ? error.message : error), { status: 500 });
  }
};
globalThis.__sloppy_register_handler(1, globalThis.__sloppy_handler_1);
