const __sloppyRuntime = globalThis.__sloppy_runtime;
if (__sloppyRuntime === undefined) {
  throw new Error("Sloppy bootstrap runtime was not loaded");
}
const { Environment, Results, data } = __sloppyRuntime;

globalThis.__sloppy_handler_1 = async () => {
  try {
    const connectionString = Environment.get("SLOPPY_POSTGRES_TEST_URL");
    if (connectionString.length === 0) {
      throw new Error("SLOPPY_POSTGRES_TEST_URL is required for the PostgreSQL live bridge lane");
    }

    const db = data.postgres.open({
      connectionString,
      capability: "data.main",
      maxConnections: 1,
    });
    try {
      await db.exec("drop table if exists sloppy_pg_bridge_cursor");
      await db.exec("create table sloppy_pg_bridge_cursor (id int generated by default as identity primary key, name text not null)");
      await db.exec("insert into sloppy_pg_bridge_cursor (name) values ($1)", ["Ada"]);
      await db.transaction(async (tx) => {
        await tx.exec("insert into sloppy_pg_bridge_cursor (name) values ($1)", ["Grace"]);
        const txCursor = await tx.queryCursor("select name from sloppy_pg_bridge_cursor order by id", [], { batchSize: 1 });
        try {
          const txNames = [];
          for await (const row of txCursor) {
            txNames.push(row.name);
          }
          if (txNames.length !== 2) {
            throw new Error("postgres transaction cursor did not read expected rows");
          }
        } finally {
          await txCursor.close();
        }
      });
      await db.exec("insert into sloppy_pg_bridge_cursor (name) select 'User-' || value::text from generate_series(1, 150) as value");

      let materializedRejected = false;
      try {
        await db.query("select id, name from sloppy_pg_bridge_cursor order by id", []);
      } catch (error) {
        materializedRejected = String(error && error.message ? error.message : error).includes("exceeded max rows");
      }

      const cursorRows = [];
      const cursor = await db.queryCursor("select id, name from sloppy_pg_bridge_cursor order by id", [], { batchSize: 32 });
      try {
        for await (const row of cursor) {
          cursorRows.push(row.name);
        }
      } finally {
        await cursor.close();
      }

      const rawCursor = await db.queryRawCursor("select id, name from sloppy_pg_bridge_cursor order by id", [], { batchSize: 16, maxRows: 2 });
      let rawFirst = null;
      let cursorMaxRowsRejected = false;
      try {
        rawFirst = await rawCursor.next();
        await rawCursor.next();
        await rawCursor.next();
      } catch (error) {
        cursorMaxRowsRejected = String(error && error.message ? error.message : error).includes("exceeded max rows");
      } finally {
        await rawCursor.close();
      }

      const pinnedCursor = await db.queryCursor("select id, name from sloppy_pg_bridge_cursor order by id", [], { batchSize: 8 });
      let poolPinned = false;
      try {
        await pinnedCursor.next();
        try {
          await db.queryOne("select 1 as ok", []);
        } catch (error) {
          poolPinned = String(error && error.message ? error.message : error).includes("pool is exhausted");
        }
      } finally {
        await pinnedCursor.close();
      }
      const afterClose = await db.queryOne("select count(*)::int as count from sloppy_pg_bridge_cursor", []);

      let cursorTimedOut = false;
      try {
        const timeoutCursor = await db.queryCursor("select pg_sleep(0.01), value from generate_series(1, 100) as value", [], { timeoutMs: 50 });
        try {
          for await (const row of timeoutCursor) {
            if (row.value < 0) {
              throw new Error("unreachable");
            }
          }
        } finally {
          await timeoutCursor.close();
        }
      } catch (error) {
        cursorTimedOut = String(error && error.message ? error.message : error).includes("deadline was exceeded");
      }

      let postgresTimedOut = false;
      try {
        await db.query("select pg_sleep(2)", [], { timeoutMs: 50 });
      } catch (error) {
        postgresTimedOut = String(error && error.message ? error.message : error).includes("deadline was exceeded");
      }
      const users = await db.query("select id, name from sloppy_pg_bridge_cursor where name in ($1, $2) order by id", ["Ada", "Grace"]);
      return Results.json({
        users,
        postgresTimedOut,
        materializedRejected,
        cursorCount: cursorRows.length,
        cursorFirst: cursorRows[0],
        cursorLast: cursorRows[cursorRows.length - 1],
        rawFirst,
        cursorMaxRowsRejected,
        poolPinned,
        afterCloseCount: afterClose.count,
        cursorTimedOut,
      });
    } finally {
      try {
        await db.exec("drop table if exists sloppy_pg_bridge_cursor");
      } catch {
      }
      db.close();
    }
  } catch (error) {
    return Results.text(String(error && error.message ? error.message : error), { status: 500 });
  }
};
globalThis.__sloppy_register_handler(1, globalThis.__sloppy_handler_1);
