const __sloppyRuntime = globalThis.__sloppy_runtime;
if (__sloppyRuntime === undefined) {
  throw new Error("Sloppy bootstrap runtime was not loaded");
}
const { Cache, Environment, Results, data } = __sloppyRuntime;

async function postgresDelay(db, seconds = "0.05") {
  await db.query(`select pg_sleep(${seconds})`, [], { timeoutMs: 1000 });
}

async function postgresCacheEvidence(db) {
  const cache = Cache.postgres(db, {
    name: "main",
    namespace: "pg_cache_a",
    table: "sloppy_pg_cache_live",
  });
  const other = Cache.postgres(db, {
    name: "other",
    namespace: "pg_cache_b",
    table: "sloppy_pg_cache_live",
  });
  await cache.clear({ dangerouslyClearAll: true });
  try {
    await cache.set("alpha", { value: "one" });
    const getOk = (await cache.get("alpha")).value === "one";
    await cache.remove("alpha");
    const removeOk = await cache.get("alpha") === undefined;

    await cache.set("ttl", "expired", { ttlMs: 1 });
    await postgresDelay(db);
    const ttlExpired = await cache.get("ttl") === undefined;

    await cache.set("slide", "ok", { slidingExpirationMs: 80 });
    await postgresDelay(db, "0.03");
    const slidingFirst = await cache.get("slide") === "ok";
    await postgresDelay(db, "0.03");
    const slidingSecond = await cache.get("slide") === "ok";
    await postgresDelay(db, "0.12");
    const slidingExpired = await cache.get("slide") === undefined;

    await cache.set("tagged", "x", { tags: ["tag-a"] });
    await cache.invalidateTag("tag-a");
    const tagInvalidated = await cache.get("tagged") === undefined;

    await cache.set("cleanup", "x", { ttlMs: 1 });
    await postgresDelay(db);
    await cache.cleanup();
    const cleanupOk = await cache.get("cleanup") === undefined;

    await cache.set("shared", "a");
    await other.set("shared", "b");
    const namespaceIsolation =
      (await cache.get("shared")) === "a" && (await other.get("shared")) === "b";

    await cache.set("hybrid", "pg");
    const hybrid = Cache.hybrid("hybrid", {
      memory: Cache.memory("front"),
      distributed: cache,
    });
    const hybridFirst = await hybrid.get("hybrid") === "pg";
    const hybridMemory = await hybrid.memory.get("hybrid") === "pg";
    const hybridGets = hybrid.stats().gets >= 1;

    return {
      getOk,
      removeOk,
      ttlExpired,
      slidingFirst,
      slidingSecond,
      slidingExpired,
      tagInvalidated,
      cleanupOk,
      namespaceIsolation,
      hybridFirst,
      hybridMemory,
      hybridGets,
    };
  } finally {
    await cache.clear({ dangerouslyClearAll: true });
  }
}

globalThis.__sloppy_handler_1 = async () => {
  try {
    const connectionString = Environment.get("SLOPPY_POSTGRES_TEST_URL");
    if (connectionString.length === 0) {
      throw new Error("SLOPPY_POSTGRES_TEST_URL is required for the PostgreSQL live bridge lane");
    }

    const db = data.postgres.open({
      connectionString,
      capability: "data.main",
      maxConnections: 1,
    });
    try {
      await db.exec("drop table if exists sloppy_pg_bridge_cursor");
      await db.exec("create table sloppy_pg_bridge_cursor (id int generated by default as identity primary key, name text not null)");
      await db.exec("insert into sloppy_pg_bridge_cursor (name) values ($1)", ["Ada"]);
      await db.transaction(async (tx) => {
        await tx.exec("insert into sloppy_pg_bridge_cursor (name) values ($1)", ["Grace"]);
        const txCursor = await tx.queryCursor("select name from sloppy_pg_bridge_cursor order by id", [], { batchSize: 1 });
        try {
          const txNames = [];
          for await (const row of txCursor) {
            txNames.push(row.name);
          }
          if (txNames.length !== 2) {
            throw new Error("postgres transaction cursor did not read expected rows");
          }
        } finally {
          await txCursor.close();
        }
      });
      await db.exec("insert into sloppy_pg_bridge_cursor (name) select 'User-' || value::text from generate_series(1, 150) as value");

      let materializedRejected = false;
      try {
        await db.query("select id, name from sloppy_pg_bridge_cursor order by id", []);
      } catch (error) {
        materializedRejected = String(error && error.message ? error.message : error).includes("exceeded max rows");
      }

      const cursorRows = [];
      const cursor = await db.queryCursor("select id, name from sloppy_pg_bridge_cursor order by id", [], { batchSize: 32 });
      try {
        for await (const row of cursor) {
          cursorRows.push(row.name);
        }
      } finally {
        await cursor.close();
      }

      const rawCursor = await db.queryRawCursor("select id, name from sloppy_pg_bridge_cursor order by id", [], { batchSize: 16, maxRows: 2 });
      let rawFirst = null;
      let cursorMaxRowsRejected = false;
      try {
        rawFirst = await rawCursor.next();
        await rawCursor.next();
        await rawCursor.next();
      } catch (error) {
        cursorMaxRowsRejected = String(error && error.message ? error.message : error).includes("exceeded max rows");
      } finally {
        await rawCursor.close();
      }

      const pinnedCursor = await db.queryCursor("select id, name from sloppy_pg_bridge_cursor order by id", [], { batchSize: 8 });
      let poolPinned = false;
      try {
        await pinnedCursor.next();
        try {
          await db.queryOne("select 1 as ok", []);
        } catch (error) {
          poolPinned = String(error && error.message ? error.message : error).includes("pool is exhausted");
        }
      } finally {
        await pinnedCursor.close();
      }
      const afterClose = await db.queryOne("select count(*)::int as count from sloppy_pg_bridge_cursor", []);

      let cursorTimedOut = false;
      try {
        const timeoutCursor = await db.queryCursor("select pg_sleep(0.01), value from generate_series(1, 100) as value", [], { timeoutMs: 50 });
        try {
          for await (const row of timeoutCursor) {
            if (row.value < 0) {
              throw new Error("unreachable");
            }
          }
        } finally {
          await timeoutCursor.close();
        }
      } catch (error) {
        cursorTimedOut = String(error && error.message ? error.message : error).includes("deadline was exceeded");
      }

      let postgresTimedOut = false;
      try {
        await db.query("select pg_sleep(2)", [], { timeoutMs: 50 });
      } catch (error) {
        postgresTimedOut = String(error && error.message ? error.message : error).includes("deadline was exceeded");
      }
      const users = await db.query("select id, name from sloppy_pg_bridge_cursor where name in ($1, $2) order by id", ["Ada", "Grace"]);
      const cacheEvidence = await postgresCacheEvidence(db);
      return Results.json({
        users,
        postgresTimedOut,
        materializedRejected,
        cursorCount: cursorRows.length,
        cursorFirst: cursorRows[0],
        cursorLast: cursorRows[cursorRows.length - 1],
        rawFirst,
        cursorMaxRowsRejected,
        poolPinned,
        afterCloseCount: afterClose.count,
        cursorTimedOut,
        cacheEvidence,
      });
    } finally {
      try {
        await db.exec("drop table if exists sloppy_pg_bridge_cursor");
      } catch {
      }
      db.close();
    }
  } catch (error) {
    return Results.text(String(error && error.message ? error.message : error), { status: 500 });
  }
};
globalThis.__sloppy_register_handler(1, globalThis.__sloppy_handler_1);
