#ifndef SLOPPY_HTTP_PROFILE_H
#define SLOPPY_HTTP_PROFILE_H

#include "sloppy/builder.h"
#include "sloppy/status.h"

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum SlHttpProfilePhase
{
    SL_HTTP_PROFILE_PHASE_SOCKET_READ = 0,
    SL_HTTP_PROFILE_PHASE_HTTP_PARSE = 1,
    SL_HTTP_PROFILE_PHASE_HEADER_CLASSIFICATION = 2,
    SL_HTTP_PROFILE_PHASE_MEDIA_TYPE_CONTENT_LENGTH = 3,
    SL_HTTP_PROFILE_PHASE_BODY_POLICY = 4,
    SL_HTTP_PROFILE_PHASE_ROUTE_DISPATCH = 5,
    SL_HTTP_PROFILE_PHASE_JSON_VALIDATION = 6,
    SL_HTTP_PROFILE_PHASE_BODY_MATERIALIZATION = 7,
    SL_HTTP_PROFILE_PHASE_V8_HANDLER_EXECUTION = 8,
    SL_HTTP_PROFILE_PHASE_NATIVE_RESPONSE_SELECTION = 9,
    SL_HTTP_PROFILE_PHASE_RESPONSE_SERIALIZATION = 10,
    SL_HTTP_PROFILE_PHASE_SOCKET_WRITE_SCHEDULING = 11,
    SL_HTTP_PROFILE_PHASE_WRITE_COMPLETION = 12,
    SL_HTTP_PROFILE_PHASE_CONNECTION_KEEP_ALIVE = 13,
    SL_HTTP_PROFILE_PHASE_DIAGNOSTICS_LOGGING = 14,
    SL_HTTP_PROFILE_PHASE_COUNT = 15
} SlHttpProfilePhase;

typedef enum SlHttpProfileCounter
{
    SL_HTTP_PROFILE_COUNTER_REQUESTS_TOTAL = 0,
    SL_HTTP_PROFILE_COUNTER_KEEP_ALIVE_REUSED = 1,
    SL_HTTP_PROFILE_COUNTER_CONNECTIONS_OPENED = 2,
    SL_HTTP_PROFILE_COUNTER_CONNECTIONS_CLOSED = 3,
    SL_HTTP_PROFILE_COUNTER_PARSER_BYTES = 4,
    SL_HTTP_PROFILE_COUNTER_HEADER_COUNT = 5,
    SL_HTTP_PROFILE_COUNTER_BODY_BYTES = 6,
    SL_HTTP_PROFILE_COUNTER_NATIVE_ROUTE_HITS = 7,
    SL_HTTP_PROFILE_COUNTER_CLASSIC_ROUTE_HITS = 8,
    SL_HTTP_PROFILE_COUNTER_NATIVE_JSON_HITS = 9,
    SL_HTTP_PROFILE_COUNTER_GENERIC_JSON_HITS = 10,
    SL_HTTP_PROFILE_COUNTER_JSON_REJECTS = 11,
    SL_HTTP_PROFILE_COUNTER_MATERIALIZATIONS = 12,
    SL_HTTP_PROFILE_COUNTER_DUPLICATE_VALIDATION_SKIPPED = 13,
    SL_HTTP_PROFILE_COUNTER_NATIVE_RESPONSE_HITS = 14,
    SL_HTTP_PROFILE_COUNTER_V8_HANDLER_CALLS = 15,
    SL_HTTP_PROFILE_COUNTER_RESPONSE_BYTES_WRITTEN = 16,
    SL_HTTP_PROFILE_COUNTER_UV_WRITE_CALLS = 17,
    SL_HTTP_PROFILE_COUNTER_UV_TRY_WRITE_CALLS = 18,
    SL_HTTP_PROFILE_COUNTER_WRITE_BUFFER_ALLOCATIONS = 19,
    SL_HTTP_PROFILE_COUNTER_RESPONSE_BUFFER_COPIES = 20,
    SL_HTTP_PROFILE_COUNTER_ARENA_RESETS = 21,
    SL_HTTP_PROFILE_COUNTER_DIAGNOSTICS_RENDERED = 22,
    SL_HTTP_PROFILE_COUNTER_BREADCRUMBS_RECORDED = 23,
    SL_HTTP_PROFILE_COUNTER_COUNT = 24
} SlHttpProfileCounter;

bool sl_http_profile_enabled(void);
uint64_t sl_http_profile_now_ns(void);
void sl_http_profile_reset(void);
void sl_http_profile_record_phase(SlHttpProfilePhase phase, uint64_t elapsed_ns);
void sl_http_profile_count(SlHttpProfileCounter counter, uint64_t amount);
SlStatus sl_http_profile_write_json(SlByteBuilder* builder);
SlStatus sl_http_profile_flush_if_requested(void);

#ifdef __cplusplus
}
#endif

#endif
