#ifndef SLOPPY_HTTP_PROFILE_H
#define SLOPPY_HTTP_PROFILE_H

#include "sloppy/builder.h"
#include "sloppy/status.h"

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum SlHttpProfilePhase
{
    SL_HTTP_PROFILE_PHASE_SOCKET_READ = 0,
    SL_HTTP_PROFILE_PHASE_HTTP_PARSE = 1,
    SL_HTTP_PROFILE_PHASE_HEADER_CLASSIFICATION = 2,
    SL_HTTP_PROFILE_PHASE_MEDIA_TYPE_CONTENT_LENGTH = 3,
    SL_HTTP_PROFILE_PHASE_BODY_POLICY = 4,
    SL_HTTP_PROFILE_PHASE_ROUTE_DISPATCH = 5,
    SL_HTTP_PROFILE_PHASE_JSON_VALIDATION = 6,
    SL_HTTP_PROFILE_PHASE_BODY_MATERIALIZATION = 7,
    SL_HTTP_PROFILE_PHASE_V8_HANDLER_EXECUTION = 8,
    SL_HTTP_PROFILE_PHASE_V8_CONTEXT_CONSTRUCTION = 9,
    SL_HTTP_PROFILE_PHASE_V8_HANDLER_CALL = 10,
    SL_HTTP_PROFILE_PHASE_V8_RESULT_CONVERSION = 11,
    SL_HTTP_PROFILE_PHASE_V8_RESULT_CONSTRUCTION = 12,
    SL_HTTP_PROFILE_PHASE_V8_JSON_STRINGIFY = 13,
    SL_HTTP_PROFILE_PHASE_NATIVE_RESPONSE_SELECTION = 14,
    SL_HTTP_PROFILE_PHASE_RESPONSE_SERIALIZATION = 15,
    SL_HTTP_PROFILE_PHASE_SOCKET_WRITE_SCHEDULING = 16,
    SL_HTTP_PROFILE_PHASE_WRITE_COMPLETION = 17,
    SL_HTTP_PROFILE_PHASE_CONNECTION_KEEP_ALIVE = 18,
    SL_HTTP_PROFILE_PHASE_DIAGNOSTICS_LOGGING = 19,
    SL_HTTP_PROFILE_PHASE_V8_HANDLER_LOOKUP = 20,
    SL_HTTP_PROFILE_PHASE_V8_CONTEXT_BASE_OBJECT = 21,
    SL_HTTP_PROFILE_PHASE_V8_REQUEST_FACADE = 22,
    SL_HTTP_PROFILE_PHASE_V8_ROUTE_PARAMS_MATERIALIZATION = 23,
    SL_HTTP_PROFILE_PHASE_V8_QUERY_MATERIALIZATION = 24,
    SL_HTTP_PROFILE_PHASE_V8_HEADERS_MATERIALIZATION = 25,
    SL_HTTP_PROFILE_PHASE_V8_BODY_FACADE_MATERIALIZATION = 26,
    SL_HTTP_PROFILE_PHASE_V8_BODY_JSON_MATERIALIZATION = 27,
    SL_HTTP_PROFILE_PHASE_V8_SERVICES_MATERIALIZATION = 28,
    SL_HTTP_PROFILE_PHASE_V8_PROMISE_AWAIT = 29,
    SL_HTTP_PROFILE_PHASE_V8_EXCEPTION_MAPPING = 30,
    SL_HTTP_PROFILE_PHASE_COUNT = 31
} SlHttpProfilePhase;

typedef enum SlHttpProfileCounter
{
    SL_HTTP_PROFILE_COUNTER_REQUESTS_TOTAL = 0,
    SL_HTTP_PROFILE_COUNTER_KEEP_ALIVE_REUSED = 1,
    SL_HTTP_PROFILE_COUNTER_CONNECTIONS_OPENED = 2,
    SL_HTTP_PROFILE_COUNTER_CONNECTIONS_CLOSED = 3,
    SL_HTTP_PROFILE_COUNTER_PARSER_BYTES = 4,
    SL_HTTP_PROFILE_COUNTER_HEADER_COUNT = 5,
    SL_HTTP_PROFILE_COUNTER_BODY_BYTES = 6,
    SL_HTTP_PROFILE_COUNTER_NATIVE_ROUTE_HITS = 7,
    SL_HTTP_PROFILE_COUNTER_CLASSIC_ROUTE_HITS = 8,
    SL_HTTP_PROFILE_COUNTER_NATIVE_JSON_HITS = 9,
    SL_HTTP_PROFILE_COUNTER_GENERIC_JSON_HITS = 10,
    SL_HTTP_PROFILE_COUNTER_JSON_REJECTS = 11,
    SL_HTTP_PROFILE_COUNTER_MATERIALIZATIONS = 12,
    SL_HTTP_PROFILE_COUNTER_DUPLICATE_VALIDATION_SKIPPED = 13,
    SL_HTTP_PROFILE_COUNTER_NATIVE_RESPONSE_HITS = 14,
    SL_HTTP_PROFILE_COUNTER_V8_HANDLER_CALLS = 15,
    SL_HTTP_PROFILE_COUNTER_RESPONSE_BYTES_WRITTEN = 16,
    SL_HTTP_PROFILE_COUNTER_UV_WRITE_CALLS = 17,
    SL_HTTP_PROFILE_COUNTER_UV_TRY_WRITE_CALLS = 18,
    SL_HTTP_PROFILE_COUNTER_WRITE_BUFFER_ALLOCATIONS = 19,
    SL_HTTP_PROFILE_COUNTER_RESPONSE_BUFFER_COPIES = 20,
    SL_HTTP_PROFILE_COUNTER_ARENA_RESETS = 21,
    SL_HTTP_PROFILE_COUNTER_DIAGNOSTICS_RENDERED = 22,
    SL_HTTP_PROFILE_COUNTER_BREADCRUMBS_RECORDED = 23,
    SL_HTTP_PROFILE_COUNTER_NATIVE_RESPONSE_ELIGIBLE = 24,
    SL_HTTP_PROFILE_COUNTER_V8_HANDLER_CACHE_HITS = 25,
    SL_HTTP_PROFILE_COUNTER_V8_HANDLER_CACHE_MISSES = 26,
    SL_HTTP_PROFILE_COUNTER_CTX_CREATED = 27,
    SL_HTTP_PROFILE_COUNTER_ROUTE_PARAMS_MATERIALIZED = 28,
    SL_HTTP_PROFILE_COUNTER_QUERY_MATERIALIZED = 29,
    SL_HTTP_PROFILE_COUNTER_HEADERS_MATERIALIZED = 30,
    SL_HTTP_PROFILE_COUNTER_BODY_FACADE_MATERIALIZED = 31,
    SL_HTTP_PROFILE_COUNTER_BODY_JSON_MATERIALIZED = 32,
    SL_HTTP_PROFILE_COUNTER_SERVICES_MATERIALIZED = 33,
    SL_HTTP_PROFILE_COUNTER_SYNC_RETURNS = 34,
    SL_HTTP_PROFILE_COUNTER_PROMISE_RETURNS = 35,
    SL_HTTP_PROFILE_COUNTER_RESULT_DESCRIPTOR_CONVERSIONS = 36,
    SL_HTTP_PROFILE_COUNTER_PLAIN_VALUE_CONVERSIONS = 37,
    SL_HTTP_PROFILE_COUNTER_RESULTS_JSON_CONVERSIONS = 38,
    SL_HTTP_PROFILE_COUNTER_RESULTS_TEXT_CONVERSIONS = 39,
    SL_HTTP_PROFILE_COUNTER_RESULTS_STATUS_CONVERSIONS = 40,
    SL_HTTP_PROFILE_COUNTER_RESULTS_PROBLEM_CONVERSIONS = 41,
    SL_HTTP_PROFILE_COUNTER_JSON_STRINGIFY_CALLS = 42,
    SL_HTTP_PROFILE_COUNTER_EXCEPTION_COUNT = 43,
    SL_HTTP_PROFILE_COUNTER_NO_JS_RESPONSE_PLAN_HITS = 44,
    SL_HTTP_PROFILE_COUNTER_NO_JS_RESPONSE_PLAN_MISSES = 45,
    SL_HTTP_PROFILE_COUNTER_NATIVE_STATIC_RESPONSE_HITS = 46,
    SL_HTTP_PROFILE_COUNTER_GENERIC_FALLBACKS = 47,
    SL_HTTP_PROFILE_COUNTER_COUNT = 48
} SlHttpProfileCounter;

bool sl_http_profile_enabled(void);
uint64_t sl_http_profile_now_ns(void);
void sl_http_profile_reset(void);
void sl_http_profile_record_phase(SlHttpProfilePhase phase, uint64_t elapsed_ns);
void sl_http_profile_count(SlHttpProfileCounter counter, uint64_t amount);
SlStatus sl_http_profile_write_json(SlByteBuilder* builder);
SlStatus sl_http_profile_flush_if_requested(void);

#ifdef __cplusplus
}
#endif

#endif
