#ifndef SLOPPY_HTTP2_MAPPING_H
#define SLOPPY_HTTP2_MAPPING_H

#include "sloppy/arena.h"
#include "sloppy/bytes.h"
#include "sloppy/diagnostics.h"
#include "sloppy/http2_session.h"
#include "sloppy/http_backend.h"
#include "sloppy/http_response.h"
#include "sloppy/status.h"

#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Converts validated HTTP/2 pseudo/regular headers into the existing Sloppy request
 * lifecycle contract. The returned request owns copied header/path/body data in `arena`.
 */
SlStatus sl_http2_request_from_headers(SlArena* arena, SlHttpConnection* connection,
                                       const SlHttp2HeaderList* headers, SlBytes body,
                                       SlHttpRequestLifecycle* out_request, SlDiag* out_diag);

/*
 * Converts a native response descriptor into HTTP/2 response headers plus DATA bytes.
 * Connection-specific HTTP/1 headers remain rejected; Content-Type and Content-Length are
 * generated by this mapper.
 */
SlStatus sl_http2_response_to_headers(SlArena* arena, const SlHttpResponse* response,
                                      bool suppress_body, size_t max_body_bytes,
                                      SlHttp2HeaderList* out_headers, SlBytes* out_body);

#ifdef __cplusplus
}
#endif

#endif
